// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ssa_nutiling
NumericVector ssa_nutiling(NumericVector a, NumericMatrix nu, int j);
RcppExport SEXP _fastgssa_ssa_nutiling(SEXP aSEXP, SEXP nuSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(ssa_nutiling(a, nu, j));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP fastgssa_ssa_nutiling(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_fastgssa_ssa_nutiling", (DL_FUNC) &_fastgssa_ssa_nutiling, 3},
    {"fastgssa_ssa_nutiling", (DL_FUNC) &fastgssa_ssa_nutiling, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastgssa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
