# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_ode_em <- function(tau, noise_strength) {
    .Call('_gillespie_make_ode_em', PACKAGE = 'gillespie', tau, noise_strength)
}

simulate <- function(num_functions, propensity_funs, ssa_method, initial_state, params, nu_i, nu_p, nu_x, final_time, census_interval, stop_on_neg_state, buffer_size, sim_name, max_walltime, log_propensity, log_firings, log_buffer, verbose, console_interval) {
    .Call('_gillespie_simulate', PACKAGE = 'gillespie', num_functions, propensity_funs, ssa_method, initial_state, params, nu_i, nu_p, nu_x, final_time, census_interval, stop_on_neg_state, buffer_size, sim_name, max_walltime, log_propensity, log_firings, log_buffer, verbose, console_interval)
}

test_ssa_step <- function(ssa_alg, state, propensity, nu_i, nu_p, nu_x) {
    .Call('_gillespie_test_ssa_step', PACKAGE = 'gillespie', ssa_alg, state, propensity, nu_i, nu_p, nu_x)
}

make_ssa_btl <- function(mean_firings) {
    .Call('_gillespie_make_ssa_btl', PACKAGE = 'gillespie', mean_firings)
}

make_ssa_direct <- function() {
    .Call('_gillespie_make_ssa_direct', PACKAGE = 'gillespie')
}

make_ssa_etl <- function(tau) {
    .Call('_gillespie_make_ssa_etl', PACKAGE = 'gillespie', tau)
}

