# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_ode_em <- function(tau, noise_strength) {
    .Call('_gillespie_make_ode_em', PACKAGE = 'gillespie', tau, noise_strength)
}

simulate <- function(propensity_funs, num_functions, ssa_alg, initial_state, params, nu_i, nu_p, nu_x, final_time, census_interval, buffer_size, sim_name, max_walltime, store_propensity, store_firings, store_buffer, verbose, console_interval) {
    .Call('_gillespie_simulate', PACKAGE = 'gillespie', propensity_funs, num_functions, ssa_alg, initial_state, params, nu_i, nu_p, nu_x, final_time, census_interval, buffer_size, sim_name, max_walltime, store_propensity, store_firings, store_buffer, verbose, console_interval)
}

make_ssa_btl <- function(f) {
    .Call('_gillespie_make_ssa_btl', PACKAGE = 'gillespie', f)
}

make_ssa_direct <- function() {
    .Call('_gillespie_make_ssa_direct', PACKAGE = 'gillespie')
}

make_ssa_etl <- function(tau) {
    .Call('_gillespie_make_ssa_etl', PACKAGE = 'gillespie', tau)
}

