on:
  push:
    branches:
      - master
      - devel
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 1"

name: build-docker

jobs:
  build_containers:
    runs-on: 'ubuntu-latest'
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: build container

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          docker build -t dynbuild -f docker/Dockerfile --build-arg GITHUB_PAT=${{ secrets.PAT }} --build-arg=GITHUB_BRANCH=$BRANCH .
          docker tag dynbuild rcannood/gillespiessa2:$BRANCH
          if [[ $BRANCH == "master" ]] ; then
            # docker tag dynbuild rcannood/gillespiessa2:$TAG
            docker tag dynbuild rcannood/gillespiessa2:latest
          fi

      - name: Push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push rcannood/gillespiessa2
