on:
  push:
    branches:
      - master
      - devel
  schedule:
    - cron: "0 0 * * 1"

name: docker_build

jobs:
  build_containers:
    runs-on: 'ubuntu-latest'
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: build container

    steps:
      - uses: actions/checkout@v2
      
      - name: Configure environment variables
        run: |
          VERSION=`cat DESCRIPTION | grep Version | sed 's#.*: ##'`
          BRANCH="${GITHUB_REF#refs/heads/}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Build
        run: |
          docker build -t rcannood/gillespiessa2:$BRANCH -f docker/Dockerfile .
          if [[ $BRANCH == "master" ]] ; then
            docker tag rcannood/gillespiessa2:$BRANCH rcannood/gillespiessa2:$VERSION
            docker tag rcannood/gillespiessa2:$BRANCH rcannood/gillespiessa2:latest
          fi

      - name: Push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push rcannood/gillespiessa2:$BRANCH
          if [[ $BRANCH == "master" ]] ; then
            docker push rcannood/gillespiessa2:$VERSION
            docker push rcannood/gillespiessa2:latest
          fi
